//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinCI.UI.Languages
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource_vi
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_vi()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XamarinCI.UI.Languages.AppResource.vi", typeof(AppResource_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string LoginWelcome
        {
            get
            {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }

        internal static string LoginMainButton
        {
            get
            {
                return ResourceManager.GetString("LoginMainButton", resourceCulture);
            }
        }

        internal static string LoginUser
        {
            get
            {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }

        internal static string LoginPassword
        {
            get
            {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }

        internal static string LoginLocalAuthButton
        {
            get
            {
                return ResourceManager.GetString("LoginLocalAuthButton", resourceCulture);
            }
        }

        internal static string HomePageTitle
        {
            get
            {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }

        internal static string HomeTabTitle
        {
            get
            {
                return ResourceManager.GetString("HomeTabTitle", resourceCulture);
            }
        }

        internal static string HomeSearchPlaceholder
        {
            get
            {
                return ResourceManager.GetString("HomeSearchPlaceholder", resourceCulture);
            }
        }

        internal static string PhotosPageTitle
        {
            get
            {
                return ResourceManager.GetString("PhotosPageTitle", resourceCulture);
            }
        }

        internal static string PhotosTabTitle
        {
            get
            {
                return ResourceManager.GetString("PhotosTabTitle", resourceCulture);
            }
        }

        internal static string SettingPageTitle
        {
            get
            {
                return ResourceManager.GetString("SettingPageTitle", resourceCulture);
            }
        }

        internal static string SettingTabTitle
        {
            get
            {
                return ResourceManager.GetString("SettingTabTitle", resourceCulture);
            }
        }

        internal static string SettingLogoutButton
        {
            get
            {
                return ResourceManager.GetString("SettingLogoutButton", resourceCulture);
            }
        }

        internal static string PhotoDetailPageTitle
        {
            get
            {
                return ResourceManager.GetString("PhotoDetailPageTitle", resourceCulture);
            }
        }

        internal static string ValidateUserRequired
        {
            get
            {
                return ResourceManager.GetString("ValidateUserRequired", resourceCulture);
            }
        }

        internal static string ValidateUserMinLength
        {
            get
            {
                return ResourceManager.GetString("ValidateUserMinLength", resourceCulture);
            }
        }

        internal static string ValidateUserMaxLength
        {
            get
            {
                return ResourceManager.GetString("ValidateUserMaxLength", resourceCulture);
            }
        }

        internal static string ValidatePasswordRequired
        {
            get
            {
                return ResourceManager.GetString("ValidatePasswordRequired", resourceCulture);
            }
        }

        internal static string ValidatePasswordMinLength
        {
            get
            {
                return ResourceManager.GetString("ValidatePasswordMinLength", resourceCulture);
            }
        }

        internal static string LogoutConfirm
        {
            get
            {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }

        internal static string ChangeLanguageConfirm
        {
            get
            {
                return ResourceManager.GetString("ChangeLanguageConfirm", resourceCulture);
            }
        }

        internal static string MessageTitleInfo
        {
            get
            {
                return ResourceManager.GetString("MessageTitleInfo", resourceCulture);
            }
        }

        internal static string MessageTitleConfirm
        {
            get
            {
                return ResourceManager.GetString("MessageTitleConfirm", resourceCulture);
            }
        }

        internal static string MessageTitleWarning
        {
            get
            {
                return ResourceManager.GetString("MessageTitleWarning", resourceCulture);
            }
        }

        internal static string MessageTitleError
        {
            get
            {
                return ResourceManager.GetString("MessageTitleError", resourceCulture);
            }
        }

        internal static string MessageButtonOk
        {
            get
            {
                return ResourceManager.GetString("MessageButtonOk", resourceCulture);
            }
        }

        internal static string MessageButtonCancel
        {
            get
            {
                return ResourceManager.GetString("MessageButtonCancel", resourceCulture);
            }
        }
    }
}
